version: "3.7"
services:
  api_service:
    image: "karuna/karuna-pages:0.0.1-SNAPSHOT"
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql_db
    command: sh -c './wait-for mysql_db:3306 -- npm start'
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/karuna_pages
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: nh34KL92wz0qlag28
      SPRING_SECURITY_USER_PASSWORD: password
  mysql_db:
    platform: linux/x86_64
    image: "mysql:5.7"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: karuna_pages
      MYSQL_ROOT_PASSWORD: nh34KL92wz0qlag28
    volumes:
      - ./db-backup/db:/var/lib/mysql