name: Karuna Pages API Build

on:
  push:
    branches:
      - develop
      - production
      - develop-deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: kamiazya/setup-graphviz@v1

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Login to Github Packages Docker
        uses: azure/docker-login@v1
        with:
          login-server: 'docker.pkg.github.com'
          username: ${{ secrets.KARUNA_DOCKER_USERNAME }}
          password: ${{ secrets.KARUNA_DOCKER_PASSWORD }}

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Gradlew Validation
        uses: gradle/wrapper-validation-action@v1

      - name: Run Tests
        if: endsWith(github.ref, '/develop')
        run: echo "Will be running unit tests"

      - name: Configure SSH
        if: endsWith(github.ref, '/develop-deploy')
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.KARUNA_SERVER_USER }}
          SSH_KEY: ${{ secrets.KARUNA_SERVER_SSH_KEY }}
          SSH_HOST: ${{ secrets.KARUNA_SERVER_URL }}

      - name: Deploy to demo server
        run: ssh -v staging '/ubuntu/deploy-files/deploy-karuna.sh'
